package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.41

import (
	"context"

	"github.com/GoExpertCurso/Desafio-CLA/graph/model"
	"github.com/GoExpertCurso/Desafio-CLA/internal/usecase"
)

// CreateOrder is the resolver for the createOrder field.
func (r *mutationResolver) CreateOrder(ctx context.Context, input *model.OrderInput) (*model.Order, error) {
	dto := usecase.OrderInputDTO{
		ID:    input.ID,
		Price: float64(input.Price),
		Tax:   float64(input.Tax),
	}
	output, err := r.CreateOrderUseCase.Execute(dto)
	if err != nil {
		return nil, err
	}
	return &model.Order{
		ID:         output.ID,
		Price:      float64(output.Price),
		Tax:        float64(output.Tax),
		FinalPrice: float64(output.FinalPrice),
	}, nil
}

// GetOrder is the resolver for the getOrder field.
func (r *queryResolver) GetOrder(ctx context.Context, id *string) (*model.Order, error) {
	selected, err := r.GetOrdersUseCase.GetOrder(*id)
	if err != nil {
		return nil, err
	}
	order := &model.Order{
		ID:         selected.ID,
		Price:      selected.Price,
		Tax:        selected.Tax,
		FinalPrice: selected.FinalPrice,
	}

	return order, nil
}

// GetOrders is the resolver for the getOrders field.
func (r *queryResolver) GetOrders(ctx context.Context) ([]*model.Order, error) {
	orders, err := r.GetOrdersUseCase.GetOrders()
	if err != nil {
		return nil, err
	}
	var ordersModel []*model.Order
	for _, or := range orders {
		ordersModel = append(ordersModel, &model.Order{
			ID:         or.ID,
			Price:      or.Price,
			Tax:        or.Tax,
			FinalPrice: or.FinalPrice,
		})
	}

	return ordersModel, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
