POST http://localhost:8000/order HTTP/1.1
Host: localhost:8000
Content-Type: application/json

{
    "id":"e3687953-5668-4092-93a3-d652b8797a60",
    "price": 3776.5,
    "tax": 0.5
}

###

GET http://localhost:8000/orders HTTP/1.1

Host: localhost:8000
Content-Type: application/json